### ISSUE TITLE
Allow user to manually select IP address.

### ISSUE THREAD

**Issue by henrikx** [waynepiekarski/XPlaneCDU#1]
Relying on X-Plane BECN signals is unreliable on some devices and set ups. An old phone I tried the app on, wouldn't connect, even if I could see in Wireshark that X-Plane was sending BECN signals. That phone was properly connected to the network and didn't have any firewall that I know of. My newer phone connected just fine. Another problem I had, is that I have some virtual network interfaces on my computer for use with Hyper-V. When they were active (I had to disable them), X-Plane wouldn't send BECN broadcasts to the right interface. I didn't find much documentation on selecting which interface X-Plane should use for this. Using a manual connect method can be easier for some users, like myself. Thanks.

**Comment by waynepiekarski** [comment]
Yeah, I've noticed quite a few people are reporting problems with multicast and BECN detection. I'm currently working on a change which will add support for you to specify the hostname of the X-Plane machine manually, which will hopefully resolve all these issues. Its almost done but I need to debug one remaining issue and then test it. Thanks for the feedback.

**Comment by waynepiekarski** [comment]
This is now fixed in the latest master branch. I have pushed out an update to Google Play https://play.google.com/store/apps/details?id=net.waynepiekarski.xplanecdu&hl=en
