### ISSUE TITLE
LevelUp 737 not supported

### ISSUE THREAD

**Issue by BradyBrother100** [waynepiekarski/XPlaneCDU#9]
Hi,
Testing the new LevelUp 737 showed that XplaneCDU does not recognize that the LevelUp 737 uses the same systems as the Zibo thus not being compatible. Are there any plans to support the LevelUp 737s?

Thanks!
Brady

**Comment by waynepiekarski** [comment]
Do you have a link to where I can download the aircraft?

The current detection is done here: https://github.com/waynepiekarski/XPlaneCDU/blob/master/app/src/main/java/net/waynepiekarski/xplanecdu/MainActivity.kt#L831

As a quick hack, you could search for acf_descrip in the aircraft .acf files and edit it to "Boeing 737-800X" and that should trick XPlaneCDU into working until I can release a new version.

**Comment by BradyBrother100** [comment]
https://forum.thresholdx.net/files/file/1298-boeing-737ng-series/

They added a feature in the tablet to change the FMC button layout. For example, instead of having separate buttons for CLB, CRZ, and DES, there is only a VNAV button. But, you can choose between which layout you want to use.

Thanks,
Brady

**Comment by BradyBrother100** [comment]
Also, the .zip that

**Comment by BradyBrother100** [comment]
Also, the .zip that you download comes with the -600, -700, -800, -900, and -900 ER all in one folder.

**Comment by waynepiekarski** [comment]
Looks like these are the aircraft filenames and the names used by XPlaneCDU:
$ grep "acf/_descrip" *.acf
737_60NG.acf:P acf/_descrip Boeing 737-600NG
737_70NG.acf:P acf/_descrip Boeing 737-700NG
737_80NG.acf:P acf/_descrip Boeing 737-800NG
737_90NG.acf:P acf/_descrip Boeing 737-900NG
737_9ENG.acf:P acf/_descrip Boeing 737-900ER

I will need to add support for this and republish a new XPlaneCDU.

**Comment by BradyBrother100** [comment]
Cool! 
Thanks!
Brady

**Comment by waynepiekarski** [comment]
Proposed changes at https://github.com/waynepiekarski/XPlaneCDU/commit/29d8558e339b7106fe269a754560020b9e1dd960
Waiting for upload to Google Play.

**Comment by waynepiekarski** [comment]
The new release of XPlaneCDU is now available on Google Play: https://play.google.com/store/apps/details?id=net.waynepiekarski.xplanecdu&hl=en_US&gl=US
Once you have version 2022010414 then you should be able to try this. Please tell me if it works for you.

**Comment by n452mk** [comment]
what about iOs? thanks.

**Comment by waynepiekarski** [comment]
I'm not an iOS developer. XPlaneCDU is only for Android.
